ARG BUILD_IMG
ARG RUNTIME_IMG

FROM ${BUILD_IMG} AS build_env

ARG FRAMEWORK
ARG NO_RESTORE_FLAG
ARG RUNTIME_IDENTIFIER

WORKDIR test_app
RUN dotnet new web --framework ${FRAMEWORK}
RUN mkdir -p $HOME/.nuget/packages
RUN dotnet restore --source $HOME/.nuget/packages -p:RuntimeIdentifiers=${RUNTIME_IDENTIFIER}
RUN dotnet publish --configuration Release ${NO_RESTORE_FLAG} --output /app -r ${RUNTIME_IDENTIFIER}

FROM ${RUNTIME_IMG}
EXPOSE 80 443
WORKDIR /app
COPY --from=build_env /app .
ENTRYPOINT ["./test_app"]

