FROM {image}

ARG FRAMEWORK

WORKDIR test
RUN dotnet new web --framework $env:FRAMEWORK
RUN dotnet restore --source ${env:USERPROFILE}/.nuget/packages "/p:RuntimeIdentifiers=win7-x64"
RUN dotnet build
