FROM {image}

# Switch to cmd shell to have consistency since this Dockerfile is used across multiple
# base images which have different shells (due to nanoserver base image).
SHELL ["cmd", "/S", "/C"]

ARG FRAMEWORK

WORKDIR test
RUN dotnet new web --framework %FRAMEWORK%
RUN mkdir %USERPROFILE%/.nuget/
RUN mkdir %USERPROFILE%/.nuget/packages
RUN dotnet restore --source %USERPROFILE%/.nuget/packages -p:RuntimeIdentifiers=win7-x64
RUN dotnet build
