FROM {image}

ARG FRAMEWORK
ARG BUILD_ARGS
ARG RUNTIME_IDENTIFIER

WORKDIR test
RUN dotnet new web --framework $FRAMEWORK
RUN mkdir -p $HOME/.nuget/packages
RUN dotnet restore --source $HOME/.nuget/packages -p:RuntimeIdentifiers=$RUNTIME_IDENTIFIER
RUN dotnet build $BUILD_ARGS
