FROM {image}

ARG FRAMEWORK
ARG BUILD_ARGS

WORKDIR test
RUN dotnet new web --framework $FRAMEWORK
RUN dotnet restore --source $HOME/.nuget/packages "/p:RuntimeIdentifiers=debian.8-x64"
RUN dotnet build $BUILD_ARGS
