ARG BUILD_IMG
ARG RUNTIME_IMG

FROM ${BUILD_IMG} AS build_env

# Switch to cmd shell to have consistency since this Dockerfile is used across multiple
# base images which have different shells (due to nanoserver base image).
SHELL ["cmd", "/S", "/C"]

ARG FRAMEWORK
ARG NO_RESTORE_FLAG

WORKDIR test_app
RUN dotnet new web --framework %FRAMEWORK%
RUN if not exist "%USERPROFILE%/.nuget/" mkdir "%USERPROFILE%/.nuget/"
RUN if not exist "%USERPROFILE%/.nuget/packages" mkdir "%USERPROFILE%/.nuget/packages"
RUN dotnet restore --source "%USERPROFILE%/.nuget/packages"
RUN dotnet publish --configuration Release %NO_RESTORE_FLAG% --output /app

FROM ${RUNTIME_IMG}
EXPOSE 80 443
WORKDIR /app
COPY --from=build_env /app .
ENTRYPOINT ["dotnet", "test_app.dll"]

