FROM {image}

# Container admin user may be required to write to mounted volumes
USER ContainerAdministrator

# Switch to cmd shell to have consistency since this Dockerfile is used across multiple
# base images which have different shells (due to nanoserver base image).
SHELL ["cmd", "/S", "/C"]

ARG FRAMEWORK
ARG BUILD_ARGS

WORKDIR test
RUN dotnet new web --framework %FRAMEWORK%
RUN if not exist "%USERPROFILE%/.nuget/" mkdir "%USERPROFILE%/.nuget/"
RUN if not exist "%USERPROFILE%/.nuget/packages" mkdir "%USERPROFILE%/.nuget/packages"
RUN dotnet restore --source "%USERPROFILE%/.nuget/packages" -p:RuntimeIdentifiers=win7-x64
RUN dotnet build %BUILD_ARGS%
