#!/bin/bash

set -e

tagName="$DOCKER_REPO:latest"
echo "Pushing tag: '$tagName'"
docker tag $IMAGE_NAME $tagName
docker push $tagName

tagName="$DOCKER_REPO:1.1.0-msbuild-rc4"
echo "Pushing tag: '$tagName'"
docker tag $IMAGE_NAME $tagName
docker push $tagName
