#!/bin/bash

set -e

tagName="$DOCKER_REPO:1.1.0-msbuild"
echo "Pushing tag: '$tagName'"
docker tag $IMAGE_NAME $tagName
docker push $tagName

tagName="$DOCKER_REPO:1.0-1.1"
echo "Pushing tag: '$tagName'"
docker tag $IMAGE_NAME $tagName
docker push $tagName
