#!/bin/bash

set -e

tagName="$DOCKER_REPO:2"
echo "Pushing tag: '$tagName'"
docker tag $IMAGE_NAME $tagName
docker push $tagName

tagName="$DOCKER_REPO:2.0.0-preview1"
echo "Pushing tag: '$tagName'"
docker tag $IMAGE_NAME $tagName
docker push $tagName
