#!/bin/bash

set -e

tagName="$DOCKER_REPO:1.0-2.0-preview1"
echo "Pushing tag: '$tagName'"
docker tag $IMAGE_NAME $tagName
docker push $tagName

tagName="$DOCKER_REPO:1.0-2.0-preview1-2017-05"
echo "Pushing tag: '$tagName'"
docker tag $IMAGE_NAME $tagName
docker push $tagName
